server:
  port: "${port:8888}"

management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: elements

