server:
  port: "${port:8888}"

management:
  security:
    enabled: true
endpoints:
  shutdown:
    enabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: elements
      embedded:
        version: 4.4.14
